[tool.black]
line-length = 88
target-version = ["py310"]
include = '\.pyi?$'
extend-exclude = '''
/(
  migrations
  | venv
  | .venv
  | build
  | dist
  | staticfiles
  | media
)/
'''

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
select = [
  "E",   # pycodestyle errors
  "W",   # pycodestyle warnings
  "F",   # pyflakes
  "I",   # isort
  "B",   # flake8-bugbear
  "C4",  # flake8-comprehensions
  "TID", # flake8-tidy-imports
  "UP",  # pyupgrade
  "DJ",  # flake8-django (checagens específicas do Django)
  "RUF"  # Ruff-specific rules
]
ignore = [
  "E501"  # Line too long (Black cuida disso)
]

[tool.ruff.lint.isort]
known-first-party = ["ty_p"]
combine-as-imports = true
force-sort-within-sections = true

[tool.ruff.lint.per-file-ignores]
"**/migrations/*.py" = ["E501", "F401"]
"manage.py" = ["E501"]
"core/settings.py" = ["F401"]  # imports não usados em settings
