# Generated by Django 5.2.7 on 2025-10-03 15:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("age", models.IntegerField()),
                (
                    "biography",
                    models.TextField(
                        blank=True,
                        validators=[django.core.validators.MaxLengthValidator(200)],
                    ),
                ),
                (
                    "picture",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=35)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        validators=[django.core.validators.MaxLengthValidator(200)],
                    ),
                ),
                ("style", models.CharField(blank=True, max_length=100)),
                (
                    "cover",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="docs/")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="core.author",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Read",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read_date", models.DateField(blank=True, null=True)),
                ("evaluation", models.IntegerField(blank=True, null=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.book"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("age", models.IntegerField()),
                ("preference", models.CharField(blank=True, max_length=200)),
                (
                    "books",
                    models.ManyToManyField(
                        related_name="readers", through="core.Read", to="core.book"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="read",
            name="reader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.reader"
            ),
        ),
    ]
