# Generated by Django 5.2.7 on 2025-10-02 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("idade", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Leitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("idade", models.IntegerField()),
                ("preferencia", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "capa",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="D:\\.django\\2025.10.01\\core\\static\\core\\images",
                    ),
                ),
                ("estilo", models.CharField(blank=True, max_length=100)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livros",
                        to="core.autor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Leitura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_leitura", models.DateField(blank=True, null=True)),
                ("avaliacao", models.IntegerField(blank=True, null=True)),
                (
                    "leitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.leitor"
                    ),
                ),
                (
                    "livro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.livro"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="leitor",
            name="livros",
            field=models.ManyToManyField(
                related_name="leitores", through="core.Leitura", to="core.livro"
            ),
        ),
    ]
