# Generated by Django 5.2.7 on 2025-10-14 23:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(600)]),
        ),
    ]
